server:
  port: 8000
spring:
  application:
    name: ClientApi
  datasource:
    url: jdbc:h2:mem:clientdb
    username: client
    password: tneilc
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true