spring:
  application:
    name: WeatherApi
  datasource:
    url: jdbc:h2:mem:weatherdb;mode=oracle
    username: weather
    password: rehtaew
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true